# Generated by Django 3.0 on 2020-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='to',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('admin_site', 'Admin Site')], max_length=10),
        ),
    ]
